name: Publish Jar
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: lagassist
        settings-path: ${{ github.workspace }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts-jar
        path: ./build/libs/*